# Note, this *only* works for observing things in the future. Dealing with the pointing corrections in the analysis is not supported here.

# Set your observing times here

In [1]:
from datetime import datetime
tstart = '2017-07-10T00:00:00'
tend = '2017-07-14T00:00:00'
 
# Turn these into datetime objects

tstart = datetime.strptime(tstart, '%Y-%m-%dT%H:%M:%S')
tend = datetime.strptime(tend, '%Y-%m-%dT%H:%M:%S')

# Step 1, get the nominal RA/Dec Position for Jupiter at the start

In [2]:
from skyfield.api import Loader
from astropy.time import Time
import astropy.units as u

load = Loader('../../data')

ts = load.timescale()
planets = load('jup310.bsp')

astro_time = Time(tstart)
t = ts.from_astropy(astro_time)
jupiter, earth = planets['jupiter'], planets['earth']
astrometric = earth.at(t).observe(jupiter)
ra, dec, distance = astrometric.radec()

print(ra.to(u.deg), dec.to(u.deg))

print(tstart.timetuple().tm_year, tstart.timetuple().tm_yday)
print(tend.timetuple().tm_year, tend.timetuple().tm_yday)

193.66700549379476 deg -4.472088884951454 deg
2017 191
2017 195

# Step 2: Go run the code that figured out the unocculted periods for the RA/Dec and the date range reported above.

This works on lif. There are example shell scripts in ./orbit_engine that use the version that Karl already compiled for the nuops users.

Do:

`./get_latest_TLE.sh`

adjust the

`run_jupiter_test.sh`

script appropriately, then

`./run_jupiter_test.sh`

Check in the resulting jupiter occultation file into the repo, push it here, and them start below.

# Step 3: Parse the resulting occultation file:

In [3]:
file = '../orbit_engine/jupiter_191_195.occ'
from jupiter_planning import *
import jupiter_planning
import importlib
importlib.reload(jupiter_planning)
orbits = jupiter_planning.parse_occ(file)
orbits

                visible             occulted
0   2017-07-10 00:50:24  2017-07-10 01:46:22
1   2017-07-10 02:27:04  2017-07-10 03:23:02
2   2017-07-10 04:03:44  2017-07-10 04:59:41
3   2017-07-10 05:40:23  2017-07-10 06:36:21
4   2017-07-10 07:17:03  2017-07-10 08:13:01
5   2017-07-10 08:53:43  2017-07-10 09:49:41
6   2017-07-10 10:30:23  2017-07-10 11:26:20
7   2017-07-10 12:07:02  2017-07-10 13:03:00
8   2017-07-10 13:43:42  2017-07-10 14:39:40
9   2017-07-10 15:20:22  2017-07-10 16:16:20
10  2017-07-10 16:57:01  2017-07-10 17:52:59
11  2017-07-10 18:33:41  2017-07-10 19:29:39
12  2017-07-10 20:10:21  2017-07-10 21:06:19
13  2017-07-10 21:47:01  2017-07-10 22:42:59
14  2017-07-10 23:23:40  2017-07-11 00:19:38
15  2017-07-11 01:00:20  2017-07-11 01:56:18
16  2017-07-11 02:37:00  2017-07-11 03:32:58
17  2017-07-11 04:13:40  2017-07-11 05:09:38
18  2017-07-11 05:50:19  2017-07-11 06:46:18
19  2017-07-11 07:26:59  2017-07-11 08:22:57
20  2017-07-11 09:03:39  2017-07-11 09:59:37
21  2017-07-11 10:40:19  2017-07-11 11:36:17
22  2017-07-11 12:16:58  2017-07-11 13:12:57
23  2017-07-11 13:53:38  2017-07-11 14:49:36
24  2017-07-11 15:30:18  2017-07-11 16:26:16
25  2017-07-11 17:06:58  2017-07-11 18:02:56
26  2017-07-11 18:43:37  2017-07-11 19:39:36
27  2017-07-11 20:20:17  2017-07-11 21:16:15
28  2017-07-11 21:56:57  2017-07-11 22:52:55
29  2017-07-11 23:33:37  2017-07-12 00:29:35
30  2017-07-12 01:10:17  2017-07-12 02:06:15
31  2017-07-12 02:46:56  2017-07-12 03:42:55
32  2017-07-12 04:23:36  2017-07-12 05:19:34
33  2017-07-12 06:00:16  2017-07-12 06:56:14
34  2017-07-12 07:36:56  2017-07-12 08:32:54
35  2017-07-12 09:13:35  2017-07-12 10:09:34
36  2017-07-12 10:50:15  2017-07-12 11:46:13
37  2017-07-12 12:26:55  2017-07-12 13:22:53
38  2017-07-12 14:03:35  2017-07-12 14:59:33
39  2017-07-12 15:40:14  2017-07-12 16:36:13
40  2017-07-12 17:16:54  2017-07-12 18:12:53
41  2017-07-12 18:53:34  2017-07-12 19:49:32
42  2017-07-12 20:30:14  2017-07-12 21:26:12
43  2017-07-12 22:06:53  2017-07-12 23:02:52
44  2017-07-12 23:43:33  2017-07-13 00:39:32
45  2017-07-13 01:20:13  2017-07-13 02:16:11
46  2017-07-13 02:56:53  2017-07-13 03:52:51
47  2017-07-13 04:33:33  2017-07-13 05:29:31
48  2017-07-13 06:10:12  2017-07-13 07:06:11
49  2017-07-13 07:46:52  2017-07-13 08:42:50
50  2017-07-13 09:23:32  2017-07-13 10:19:30
51  2017-07-13 11:00:12  2017-07-13 11:56:10
52  2017-07-13 12:36:51  2017-07-13 13:32:50
53  2017-07-13 14:13:31  2017-07-13 15:09:30
54  2017-07-13 15:50:11  2017-07-13 16:46:09
55  2017-07-13 17:26:51  2017-07-13 18:22:49
56  2017-07-13 19:03:31  2017-07-13 19:59:29
57  2017-07-13 20:40:10  2017-07-13 21:36:09
58  2017-07-13 22:16:50  2017-07-13 23:12:48

# Use SkyField to get the location of Jupiter for each orbit:

In [4]:
jupiter_planning.get_jupiter_radec(orbits, load_path = '../data', outfile='jupiter_191_195_pointing.txt', parallax_correction=True)

WARNING: AstropyDeprecationWarning: astropy.utils.compat.odict.OrderedDict is now deprecated - import OrderedDict from the collections module instead [astropy.utils.compat.odict]

Total accumualted time 198133.0