# Note, this *only* works for observing things in the future. Dealing with the pointing corrections in the analysis is not supported here.

# Set your observing times here

In [1]:
from datetime import datetime
tstart = '2017-06-17T00:00:00'
tend = '2017-06-22T00:00:00'
 
# Turn these into datetime objects

tstart = datetime.strptime(tstart, '%Y-%m-%dT%H:%M:%S')
tend = datetime.strptime(tend, '%Y-%m-%dT%H:%M:%S')

# Step 1, get the nominal RA/Dec Position for Jupiter at the start

In [2]:
from skyfield.api import Loader
from astropy.time import Time
import astropy.units as u

load = Loader('../data')

ts = load.timescale()
planets = load('jup310.bsp')

astro_time = Time(tstart)
t = ts.from_astropy(astro_time)
jupiter, earth = planets['jupiter'], planets['earth']
astrometric = earth.at(t).observe(jupiter)
ra, dec, distance = astrometric.radec()

print(ra.to(u.deg), dec.to(u.deg))

print(tstart.timetuple().tm_year, tstart.timetuple().tm_yday)
print(tend.timetuple().tm_year, tend.timetuple().tm_yday)

[#################################] 100% jup310.bsp

192.54392457245072 deg -3.894209371115597 deg
2017 168
2017 173

# Step 2: Go run the code that figured out the unocculted periods for the RA/Dec and the date range reported above.

This works on lif. There are example shell scripts in ./orbit_engine that use the version that Karl already compiled for the nuops users.

Do:

`./get_latest_TLE.sh`

adjust the

`run_jupiter_test.sh`

script appropriately, then

`./run_jupiter_test.sh`

Check in the resulting jupiter occultation file into the repo, push it here, and them start below.

# Step 3: Parse the resulting occultation file:

In [3]:
file = '../orbit_engine/jupiter_168_173.occ'
from jupiter_planning import *
import jupiter_planning
import importlib
importlib.reload(jupiter_planning)
orbits = jupiter_planning.parse_occ(file)
orbits

                visible             occulted
0   2017-06-17 00:15:25  2017-06-17 01:11:13
1   2017-06-17 01:52:04  2017-06-17 02:47:53
2   2017-06-17 03:28:44  2017-06-17 04:24:33
3   2017-06-17 05:05:23  2017-06-17 06:01:12
4   2017-06-17 06:42:03  2017-06-17 07:37:52
5   2017-06-17 08:18:43  2017-06-17 09:14:32
6   2017-06-17 09:55:22  2017-06-17 10:51:12
7   2017-06-17 11:32:02  2017-06-17 12:27:51
8   2017-06-17 13:08:42  2017-06-17 14:04:31
9   2017-06-17 14:45:21  2017-06-17 15:41:11
10  2017-06-17 16:22:01  2017-06-17 17:17:50
11  2017-06-17 17:58:41  2017-06-17 18:54:30
12  2017-06-17 19:35:20  2017-06-17 20:31:10
13  2017-06-17 21:12:00  2017-06-17 22:07:49
14  2017-06-17 22:48:40  2017-06-17 23:44:29
15  2017-06-18 00:25:19  2017-06-18 01:21:09
16  2017-06-18 02:01:59  2017-06-18 02:57:48
17  2017-06-18 03:38:39  2017-06-18 04:34:28
18  2017-06-18 05:15:18  2017-06-18 06:11:08
19  2017-06-18 06:51:58  2017-06-18 07:47:47
20  2017-06-18 08:28:37  2017-06-18 09:24:27
21  2017-06-18 10:05:17  2017-06-18 11:01:07
22  2017-06-18 11:41:57  2017-06-18 12:37:46
23  2017-06-18 13:18:36  2017-06-18 14:14:26
24  2017-06-18 14:55:16  2017-06-18 15:51:06
25  2017-06-18 16:31:56  2017-06-18 17:27:45
26  2017-06-18 18:08:35  2017-06-18 19:04:25
27  2017-06-18 19:45:15  2017-06-18 20:41:05
28  2017-06-18 21:21:55  2017-06-18 22:17:44
29  2017-06-18 22:58:34  2017-06-18 23:54:24
..                  ...                  ...
44  2017-06-19 23:08:29  2017-06-20 00:04:19
45  2017-06-20 00:45:09  2017-06-20 01:40:59
46  2017-06-20 02:21:49  2017-06-20 03:17:39
47  2017-06-20 03:58:28  2017-06-20 04:54:18
48  2017-06-20 05:35:08  2017-06-20 06:30:58
49  2017-06-20 07:11:47  2017-06-20 08:07:38
50  2017-06-20 08:48:27  2017-06-20 09:44:17
51  2017-06-20 10:25:07  2017-06-20 11:20:57
52  2017-06-20 12:01:46  2017-06-20 12:57:37
53  2017-06-20 13:38:26  2017-06-20 14:34:16
54  2017-06-20 15:15:06  2017-06-20 16:10:56
55  2017-06-20 16:51:45  2017-06-20 17:47:36
56  2017-06-20 18:28:25  2017-06-20 19:24:15
57  2017-06-20 20:05:05  2017-06-20 21:00:55
58  2017-06-20 21:41:44  2017-06-20 22:37:35
59  2017-06-20 23:18:24  2017-06-21 00:14:15
60  2017-06-21 00:55:04  2017-06-21 01:50:54
61  2017-06-21 02:31:43  2017-06-21 03:27:34
62  2017-06-21 04:08:23  2017-06-21 05:04:14
63  2017-06-21 05:45:03  2017-06-21 06:40:53
64  2017-06-21 07:21:42  2017-06-21 08:17:33
65  2017-06-21 08:58:22  2017-06-21 09:54:13
66  2017-06-21 10:35:02  2017-06-21 11:30:52
67  2017-06-21 12:11:41  2017-06-21 13:07:32
68  2017-06-21 13:48:21  2017-06-21 14:44:12
69  2017-06-21 15:25:01  2017-06-21 16:20:51
70  2017-06-21 17:01:40  2017-06-21 17:57:31
71  2017-06-21 18:38:20  2017-06-21 19:34:11
72  2017-06-21 20:15:00  2017-06-21 21:10:50
73  2017-06-21 21:51:39  2017-06-21 22:47:30

[74 rows x 2 columns]

# Use SkyField to get the location of Jupiter for each orbit:

In [4]:
jupiter_planning.get_jupiter_radec(orbits, load_path = '../data', outfile='jupiter_168_173_pointing.txt', parallax_correction=True)

WARNING: AstropyDeprecationWarning: astropy.utils.compat.odict.OrderedDict is now deprecated - import OrderedDict from the collections module instead [astropy.utils.compat.odict]
[#################################] 100% deltat.data
[#################################] 100% deltat.preds
[#################################] 100% Leap_Second.dat

Total accumualted time 247893.0