# Note, this *only* works for observing things in the future. Dealing with the pointing corrections in the analysis is not supported here.

# Set your observing times here

In [1]:
from datetime import datetime
tstart = '2017-07-09T00:00:00'
tend = '2017-07-12T00:00:00'
 
# Turn these into datetime objects

tstart = datetime.strptime(tstart, '%Y-%m-%dT%H:%M:%S')
tend = datetime.strptime(tend, '%Y-%m-%dT%H:%M:%S')

# Step 1, get the nominal RA/Dec Position for Jupiter at the start

In [2]:
from skyfield.api import Loader
from astropy.time import Time
import astropy.units as u

load = Loader('../data')

ts = load.timescale()
planets = load('jup310.bsp')

astro_time = Time(tstart)
t = ts.from_astropy(astro_time)
jupiter, earth = planets['jupiter'], planets['earth']
astrometric = earth.at(t).observe(jupiter)
ra, dec, distance = astrometric.radec()

print(ra.to(u.deg), dec.to(u.deg))

print(tstart.timetuple().tm_year, tstart.timetuple().tm_yday)
print(tend.timetuple().tm_year, tend.timetuple().tm_yday)

193.59071471846357 deg -4.4357602594860674 deg
2017 190
2017 193

# Step 2: Go run the code that figured out the unocculted periods for the RA/Dec and the date range reported above.

This works on lif. There are example shell scripts in ./orbit_engine that use the version that Karl already compiled for the nuops users.

Do:

`./get_latest_TLE.sh`

adjust the

`run_jupiter_test.sh`

script appropriately, then

`./run_jupiter_test.sh`

Check in the resulting jupiter occultation file into the repo, push it here, and them start below.

# Step 3: Parse the resulting occultation file:

In [4]:
file = '../orbit_engine/jupiter_190_193.occ'
from jupiter_planning import *
import jupiter_planning
import importlib
importlib.reload(jupiter_planning)
orbits = jupiter_planning.parse_occ(file)
orbits

                visible             occulted
0   2017-07-09 00:40:27  2017-07-09 01:36:25
1   2017-07-09 02:17:06  2017-07-09 03:13:05
2   2017-07-09 03:53:46  2017-07-09 04:49:44
3   2017-07-09 05:30:26  2017-07-09 06:26:24
4   2017-07-09 07:07:06  2017-07-09 08:03:04
5   2017-07-09 08:43:45  2017-07-09 09:39:44
6   2017-07-09 10:20:25  2017-07-09 11:16:23
7   2017-07-09 11:57:05  2017-07-09 12:53:03
8   2017-07-09 13:33:44  2017-07-09 14:29:43
9   2017-07-09 15:10:24  2017-07-09 16:06:23
10  2017-07-09 16:47:04  2017-07-09 17:43:02
11  2017-07-09 18:23:44  2017-07-09 19:19:42
12  2017-07-09 20:00:23  2017-07-09 20:56:22
13  2017-07-09 21:37:03  2017-07-09 22:33:02
14  2017-07-09 23:13:43  2017-07-10 00:09:41
15  2017-07-10 00:50:22  2017-07-10 01:46:21
16  2017-07-10 02:27:02  2017-07-10 03:23:01
17  2017-07-10 04:03:42  2017-07-10 04:59:41
18  2017-07-10 05:40:22  2017-07-10 06:36:20
19  2017-07-10 07:17:01  2017-07-10 08:13:00
20  2017-07-10 08:53:41  2017-07-10 09:49:40
21  2017-07-10 10:30:21  2017-07-10 11:26:20
22  2017-07-10 12:07:01  2017-07-10 13:02:59
23  2017-07-10 13:43:40  2017-07-10 14:39:39
24  2017-07-10 15:20:20  2017-07-10 16:16:19
25  2017-07-10 16:57:00  2017-07-10 17:52:59
26  2017-07-10 18:33:40  2017-07-10 19:29:38
27  2017-07-10 20:10:19  2017-07-10 21:06:18
28  2017-07-10 21:46:59  2017-07-10 22:42:58
29  2017-07-10 23:23:39  2017-07-11 00:19:38
30  2017-07-11 01:00:19  2017-07-11 01:56:17
31  2017-07-11 02:36:58  2017-07-11 03:32:57
32  2017-07-11 04:13:38  2017-07-11 05:09:37
33  2017-07-11 05:50:18  2017-07-11 06:46:17
34  2017-07-11 07:26:58  2017-07-11 08:22:57
35  2017-07-11 09:03:37  2017-07-11 09:59:36
36  2017-07-11 10:40:17  2017-07-11 11:36:16
37  2017-07-11 12:16:57  2017-07-11 13:12:56
38  2017-07-11 13:53:37  2017-07-11 14:49:36
39  2017-07-11 15:30:16  2017-07-11 16:26:15
40  2017-07-11 17:06:56  2017-07-11 18:02:55
41  2017-07-11 18:43:36  2017-07-11 19:39:35
42  2017-07-11 20:20:16  2017-07-11 21:16:15
43  2017-07-11 21:56:55  2017-07-11 22:52:54

# Use SkyField to get the location of Jupiter for each orbit:

In [5]:
jupiter_planning.get_jupiter_radec(orbits, load_path = '../data', outfile='jupiter_190_193_pointing.txt', parallax_correction=True)

WARNING: AstropyDeprecationWarning: astropy.utils.compat.odict.OrderedDict is now deprecated - import OrderedDict from the collections module instead [astropy.utils.compat.odict]

Total accumualted time 147783.0